---
title: "Guidance"
author: "Colin Mahony"
date: "26/04/2021"
output: html_document
---


# Model and Scenario Selection Guidance for ClimateBC

Colin Mahony (colin.mahony@gov.bc.ca)<br>
Vanessa Foord (vanessa.foord@gov.bc.ca)<br>
Research Climatologists<br>
BC Ministry of Forests, Lands, Natural Resource Operations and Rural Development<br>

Released: April 26, 2021

## Purpose

This guidance is developed by the BC Ministry of Forests, Lands, Natural Resource Operations and Rural Development (FLNRORD) to provide best practices for users of ClimateBC and those evaluating projects prepared using ClimateBC data. This guidance is professional opinion and does not represent government policy. 

## Model selection

Wherever possible, climate change studies should use projections from multiple models to assess modeling uncertainties. There is broad scientific agreement that an ensemble of at least eight independent climate models are required to represent modeling uncertainties about climate change outcomes over large regions ([Pierce et al. 2009](https://www.pnas.org/content/106/21/8441), [McSweeney et al. 2014](https://link.springer.com/article/10.1007/s00382-014-2418-8), [Cannon 2015](https://journals.ametsoc.org/view/journals/clim/28/3/jcli-d-14-00636.1.xml), [Wilcke and Bärring 2016](https://www.sciencedirect.com/science/article/pii/S1364815216300020)). However, small ensembles of 3-5 GCMs may be adequate for studies that are limited to a small area or a single time of year. If a single representative projection is desired, the 13-GCM ensemble mean is likely more reliable than any single GCM projection ( [Pierce et al. 2009](https://www.pnas.org/content/106/21/8441)). 

### Recommended subsets of the 13-model ClimateBC ensemble  
The "Choose models" tab of this tool provides assistance with selecting subsets of the 13-model ClimateBC ensemble by providing a predefined order of exclusion of models for user-specified ensemble sizes. Models are excluded in two phases: first based on screening criteria to exclude models with lower value for the anticipated uses of ClimateBC data and second using the method of [Cannon (2015)](https://journals.ametsoc.org/view/journals/clim/28/3/jcli-d-14-00636.1.xml) to best represent the spread of the remaining models across all time periods and scenarios. The order of model selection is unique to each ecoprovince because the relative change projected by the models differs across the province. Smaller ensembles (<8 models) are less likely to span the range of climate changes in all variables, and should be used with caution. Users interested in a small ensemble for specific climate variables are advised to select a custom ensemble based on visual inspection of the "Choose models" tab. 

## Scenario selection

CMIP6 climate projections follow scenarios of future greenhouse gas emissions called [Shared Socioeconomic Pathways](https://www.carbonbrief.org/explainer-how-shared-socioeconomic-pathways-explore-future-climate-change) (SSPs). ClimateBC includes projections for the four major SSP scenarios: SSP1-2.6, SSP2-4.5, SSP3-7.0, and SSP5-8.5. 
SSP1-2.6 assumes strong emissions reductions (mitigation) roughly consistent with the goals of the Paris Climate Accords to limit global warming to 2<sup>o</sup>C above pre-industrial temperatures. SSP2-4.5 assumes moderate mitigation roughly consistent with current emissions policies and economic trends. SSP3-7.0 is representative of a broader range of "baseline" scenarios that assume the absence of mitigation policies, and is associated with linear increase in the rate of greenhouse gas emissions. SSP5-8.5 is at the high end of the baseline scenarios, and prescribes accelerating greenhouse gas emissions over the next several decades and end-of-century emissions more than three times higher than current emissions. 

Collectively, SSP1-2.6, SSP2-4.5, and SSP3-7.0 provide a reasonable representation of optimistic, neutral, and pessimistic outlooks on global emissions policies and socioeconomic development. We recommend against using SSP5-8.5 for impacts and adaptation research because the emissions pathway described by SSP5-8.5 is extremely unlikely based on constraints to the supply ([Ritchie and Dowlatabadi 2017](https://www.sciencedirect.com/science/article/abs/pii/S0360544217314597)) and demand ([Ritchie and Dowlatabadi 2018](https://iopscience.iop.org/article/10.1088/1748-9326/aaa494)) for high-carbon energy sources and current trends in energy economics and policy ([Hausfather and Peters 2020](https://www.nature.com/articles/d41586-020-00177-3)). SSP2-4.5 is sufficient for studies focused on the near future (the 2021-2040 period) since there is only minor differentiation between the three recommended emissions scenarios in this period relative to differences between climate models. 

## Time period selection
ClimateBC traditionally summarizes future GCM projections averaged over three 30-year periods: 2011-2040 (the “2020s”); 2041-2070 (the “2050s”); and 2071-2100 (the “2080s”). Version 7 now also includes a set of five 20-year periods for the 21st Century: 2001-2020, 2021-2040, and so on. These 20-year periods provide a cleaner differentiation between the past (pre-2021) and the future (post-2020). The 2001-2020 period also provides the opportunity for direct comparison of model simulations vs. observations, which can give important context to interpretations of future projections. ClimateBC normals for the 2001-2020 period are calulated from the historical model runs for the years 2001-2014 and the SSP scenario runs for the year 2015-2020.

When interpreting projections for the near future, it is important to recognize that GCM projections are not predictions. GCM runs used for climate change projections are initiated in the 1850s and are not directly constrained by observed climate conditions. Consequently, GCM projections are essentially as uncertain for next year as they are for 20 years into the future. Decadal climate prediction, which is analogous to weather prediction for timescales of 1-10 years, is an emerging but not yet operational science that may help to reduce the uncertainty of near-term projections ([Boer et al. 2016](https://gmd.copernicus.org/articles/9/3751/2016/)). In the meantime, it is considered best practice to use an ensemble of climate projections, such as those provided by ClimateBC, for near-term regional climate change studies ([Brekke et al. 2008](https://link.springer.com/article/10.1007/s10584-007-9388-3), [Knutti 2008](https://royalsocietypublishing.org/doi/10.1098/rsta.2008.0169), [Pierce et al. 2009](https://www.pnas.org/content/106/21/8441)). Given that the recent observed climate may differ substantially from the ensemble mean, climate change adaptation decisions for the near-term (1-10 years) should carefully consider recent observed trends in addition to climate model simulations. 

## References
Boer, G. J., D. M. Smith, C. Cassou, et al. 2016. The Decadal Climate Prediction Project (DCPP) contribution to CMIP6. Geoscientific Model Development 9:3751–3777.

Brekke, L. D., M. D. Dettinger, E. P. Maurer, and M. Anderson. 2008. Significance of model credibility in estimating climate projection distributions for regional hydroclimatological risk assessments. Climatic Change 89:371–394.

Cannon, A. J. 2015. Selecting GCM scenarios that span the range of changes in a multimodel ensemble: Application to CMIP5 climate extremes indices. Journal of Climate 28:1260–1267.

Hausfather, Z., and G. P. Peters. 2020. Emissions - the “business as usual” story is misleading. Nature 577:618–620.
IPCC. 2014. Climate Change 2014: Synthesis Report. Contribution of Working Groups I, II and III to the Fifth Assessment Report of the Intergovernmental Panel on Climate Change. Page (Core Writing Team, R. K. Pachauri, and L. A. Meyer, Eds.). Geneva, Switzerland.

IPCC. 2018. Summary for Policymakers. in V. Masson-Delmotte, P. Zhai, H.-O. Pörtner, et al., editors. Global Warming of 1.5°C. 

Knutti, R. 2008. Should we believe model predictions of future climate change? Philosophical Transactions of the Royal Society A: Mathematical, Physical and Engineering Sciences 366:4647–4664.

McSweeney, C. F., R. G. Jones, R. W. Lee, and D. P. Rowell. 2014. Selecting CMIP5 GCMs for downscaling over multiple regions. Climate Dynamics 44:3237–3260.

Pierce, D. W., T. P. Barnett, B. D. Santer, and P. J. Gleckler. 2009. Selecting global climate models for regional climate change studies. Proceedings of the National Academy of Sciences of the United States of America 106:8441–8446.

Wilcke, R. A. I., and L. Bärring. 2016. Selecting regional climate scenarios for impact modelling studies. Environmental Modelling and Software 78:191–201.

